package com.mycompany.fypmaven;

import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.SecureRandom;
import java.sql.SQLException;
import javax.swing.Timer;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class EditAccountPanel extends javax.swing.JFrame {

    UserAccs user;
    String description;
    private static final Logger logger = LogManager.getLogger();

    public EditAccountPanel() {
        initComponents();
    }

//    Overload of the constructor
    public EditAccountPanel(UserAccs user, String description) {

//      Initial setup of the frame
        initComponents();
        this.user = user;
        this.description = description;

//      Declaration of variables
        Object[] param = {description, user.getUserID()};
        String query = "SELECT * FROM accounts where description = ? AND user_id = ?";
        String username = null;
        String password = null;
        String URL = null;

        try {

//          Establishing a connection
            DB_Connection connection = new DB_Connection();
            connection.getConnection();

//          Getting the information from the database
            username = connection.executeReadQuery(query, param, "Username");
            password = connection.executeReadQuery(query, param, "Password");
            URL = connection.executeReadQuery(query, param, "URL");

        } catch (SQLException ex) {
            logger.error(ex.getMessage());
        }

//      Filling in the textboxes with their respective information
        password = password.trim();
        String decryptedpassword = GeneralFunctions.decrypt(password, user.getEncryptKey());
        TxtDescription.setText(description);
        TxtUsername.setText(username);
        TxtPassword.setText(decryptedpassword);
        TxtURL.setText(URL);

        /* Listeners */
//      Content Pane Mouse Listener
/*      Removes all focus on click*/
        getContentPane().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
            }
        });

        //      Check box Action Listener
/*      Shows the content of the password textbox*/
        checkBoxShowPassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (checkBoxShowPassword.isSelected()) {
                    TxtPassword.setEchoChar((char) 0); // Show password as plain text
                } else {
                    TxtPassword.setEchoChar('*'); // Show password as asterisks
                }
            }
        });

//      Generate Password Action Listener
/*      Changes the text of the generate password button then changes it back after a few seconds*/
        BtnGeneratePass.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BtnGeneratePass.setText("Generated");
                Timer timer = new Timer(5000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        BtnGeneratePass.setText("Generate Password");
                    }
                });
                timer.setRepeats(false); 
                timer.start();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDescription = new javax.swing.JTextField();
        LblDescription = new javax.swing.JLabel();
        LblUserName = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        BtnGeneratePass = new javax.swing.JButton();
        LblURL = new javax.swing.JLabel();
        TxtURL = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        TxtPassword = new javax.swing.JPasswordField();
        checkBoxShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtDescription.setMinimumSize(new java.awt.Dimension(37, 225));

        LblDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblDescription.setForeground(new java.awt.Color(0, 0, 0));
        LblDescription.setText("Description:");

        LblUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblUserName.setForeground(new java.awt.Color(0, 0, 0));
        LblUserName.setText("Username :");

        TxtUsername.setMinimumSize(new java.awt.Dimension(37, 225));

        LblPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Password :");

        BtnGeneratePass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BtnGeneratePass.setText("Generate Password");
        BtnGeneratePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeneratePassActionPerformed(evt);
            }
        });

        LblURL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblURL.setForeground(new java.awt.Color(0, 0, 0));
        LblURL.setText("URL :");

        BtnSave.setLabel("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        TxtPassword.setEnabled(false);

        checkBoxShowPassword.setText("Show Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBoxShowPassword)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblDescription)
                            .addGap(17, 17, 17)
                            .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(LblUserName)
                            .addGap(18, 18, 18)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LblPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblURL)
                            .addGap(25, 25, 25)
                            .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LblDescription))
                    .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(LblUserName))
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBoxShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblURL))
                    .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        
//      Declaration of variables
        String Username = TxtUsername.getText();
        String Password = TxtPassword.getText();
        String Description = TxtDescription.getText();
        String URL = TxtURL.getText();
        String UserID = user.getUserID();
        Object[] Data = {Description, UserID};
        String duplicateQuery = "SELECT Description FROM accounts WHERE Description = ? AND user_id = ?";
        Object[] exclude = {description};

//      Checks if there are any empty textboxes
        if ((Username.equals("") || Password.equals("") || Description.equals("") || URL.equals(""))) {

            GeneralFunctions.showNotification("Please ensure that all the textboxes are filled in.", "Failed");

//      Checks if there are description entered already exists within  the system   
        } else if (GeneralFunctions.checkDuplicate(Data, duplicateQuery, exclude) == true) {
            
            GeneralFunctions.showNotification("There is already an account with the same description.", "Failed");
        } else {

            
            //  Declaring variables 
            Password = GeneralFunctions.encrypt(TxtPassword.getText(), user.getEncryptKey());
            Object[] Accdata = {Description, Username, Password, URL, UserID};
            String insertQuery = "INSERT INTO accounts (Description, Username, Password, URL, user_id) VALUES (?, ?, ?, ?, ?)";
            String deletequery = "DELETE FROM accounts WHERE Description = ? AND user_ID = ?";
            Object[] deleteparam = {description, user.getUserID()};

            try {
                
                logger.info("Editing the" + description + "account");
//              Establish database connection
                DB_Connection connection = new DB_Connection();
                connection.getConnection();

//              Deletes and reinserts the data into the system
                connection.executeQuery(deletequery, deleteparam);
                connection.executeQuery(insertQuery, Accdata);
                GeneralFunctions.showNotification("Account edited", "Success");
                
//              Directs the user back to the dashboard
                Dashboard dashboard = new Dashboard(user);
                dashboard.setVisible(true);
                this.dispose();
                
                logger.info("Successfully editing the" + description + "account");
            } catch (SQLException ex) {
                logger.error(ex.getMessage());
            }

        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    //  This is the cancel process code block
    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed

        Dashboard dashboard = new Dashboard(user);
        dashboard.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCancelActionPerformed

//    This is the generate password code block
    private void BtnGeneratePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeneratePassActionPerformed

//      Declaration of variables
        String LOWERCASE = "abcdefghijklmnopqrstuvwxyz";
        String UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String DIGITS = "0123456789";
        String SPECIAL_CHARACTERS = "!@#$%^&*()_-+=<>?";
        int passwordLength = 20;
        boolean includeUppercase = true;
        boolean includeDigits = true;
        boolean includeSpecialChars = true;
        SecureRandom random = new SecureRandom();
        StringBuilder password = new StringBuilder();

        // Define the character set based on user preferences
        String characters = LOWERCASE;
        if (includeUppercase) {
            characters += UPPERCASE;
        }
        if (includeDigits) {
            characters += DIGITS;
        }
        if (includeSpecialChars) {
            characters += SPECIAL_CHARACTERS;
        }

        // Generate the password
        for (int i = 0; i < passwordLength; i++) {
            int index = random.nextInt(characters.length());
            password.append(characters.charAt(index));
        }

        //      Changing the text of the pasword textbox
        String securePassword = password.toString();
        TxtPassword.setText(securePassword);

    }//GEN-LAST:event_BtnGeneratePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccountPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnGeneratePass;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel LblDescription;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblURL;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JTextField TxtDescription;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtURL;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JCheckBox checkBoxShowPassword;
    // End of variables declaration//GEN-END:variables
}
