package com.mycompany.fypmaven;

import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class RegisterPanel extends javax.swing.JFrame {

    public RegisterPanel() {
       

//        Initial setup of the interface
        initComponents();
        LblWrongPass.setVisible(false);
        LblPassDetails.setVisible(false);
        LblPassDetailsPt2.setVisible(false);

        /* Listeners */
//      Content Panel Mouse Listeneron 
//      Removes all focus on click
        getContentPane().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
            }
        });

//        Username Textbox Focus Listener
//        Clears the username textbox on focus and fills it back on focus loss
        TxtUsername.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (TxtUsername.getText().equals("Enter your Username")) {
                    TxtUsername.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (TxtUsername.getText().isEmpty()) {
                    TxtUsername.setText("Enter your Username");
                    TxtUsername.setForeground(Color.GRAY);
                }
            }
        });

//      Password textbox focus listener
//      Clears the password textbox on focus 
        TxtPassword.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                    TxtPassword.setText("");
            }
        });
        
//      Confirem Password TextBox Focus Listener
        //Clears the password textbox on focus 
        TxtConfirmPassword.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                    TxtConfirmPassword.setText("");
            }
        });

//      Confirm Password TextBox Document Listener
//      Checks if the values of password and confirm passwords are the same
        TxtConfirmPassword.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkPasswords();
            }

            private void checkPasswords() {
                String password = TxtPassword.getText();
                String confirmPassword = TxtConfirmPassword.getText();
                if (!password.equals(confirmPassword)) {
                    LblWrongPass.setVisible(true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblUsername = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        LblPassDetails = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        BtnRegister = new javax.swing.JButton();
        LblWrongPass = new javax.swing.JLabel();
        LblPassDetailsPt2 = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        TxtPassword = new javax.swing.JPasswordField();
        TxtConfirmPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblUsername.setForeground(new java.awt.Color(0, 0, 0));
        LblUsername.setText("Username");
        getContentPane().add(LblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        LblPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Password");
        getContentPane().add(LblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        LblPassDetails.setForeground(new java.awt.Color(255, 0, 51));
        LblPassDetails.setText("Please ensure that password has at least 1 upper case letter,");
        LblPassDetails.setFocusable(false);
        getContentPane().add(LblPassDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 358, 16));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 38));

        TxtUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtUsername.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsername.setText("Enter your Username");
        getContentPane().add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 37, 359, 38));

        BtnRegister.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnRegister.setText("Register");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 117, 37));

        LblWrongPass.setForeground(new java.awt.Color(255, 51, 51));
        LblWrongPass.setText("The passwords entered are not the same");
        LblWrongPass.setFocusable(false);
        getContentPane().add(LblWrongPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        LblPassDetailsPt2.setForeground(new java.awt.Color(255, 0, 51));
        LblPassDetailsPt2.setText(" 1 lower case letter, 1 number, and 1 special character ");
        LblPassDetailsPt2.setFocusable(false);
        getContentPane().add(LblPassDetailsPt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 358, 16));

        BtnCancel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 250, 117, 37));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 291, -1, 7));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 291, -1, -1));
        getContentPane().add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 93, 359, 38));
        getContentPane().add(TxtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 181, 359, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    This is the register button code block
    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        
//      Declaration of variables
        String Username = TxtUsername.getText();
        String Password = TxtPassword.getText();
        String confirmPassword = TxtConfirmPassword.getText();
        Object[] Param = {Username};
       
//      Checks if the values of the password textbox and confirm password textbox are the same
        if (Password.equals(confirmPassword)) {
            
            //  Checks if the password entered is valid
            if (GeneralFunctions.isValidPassword(Password)) {

                String duplicateQuery = "SELECT Name FROM user_accounts WHERE Name = ?";

//      Checks if there are username entered already exists within  the system   
                if (GeneralFunctions.checkDuplicate(Param, duplicateQuery) == true) {

                    GeneralFunctions.showNotification("There is already an user with that username.", "Failed");

                } else {

//                  Creates the user object
                    UserAccs user = new UserAccs(Username, Password);

//                  Redirects the user to the recoveryPhrase frame
                    this.dispose();
                    RecoveryPhrase recovery = new RecoveryPhrase(user);
                    recovery.setVisible(true);
                }
            } else {
                LblPassDetails.setVisible(true);
                LblPassDetailsPt2.setVisible(true);

            }
        }
    }//GEN-LAST:event_BtnRegisterActionPerformed

        //  This is the cancel process code block
    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        this.dispose();
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
    }//GEN-LAST:event_BtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JLabel LblPassDetails;
    private javax.swing.JLabel LblPassDetailsPt2;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JLabel LblWrongPass;
    private javax.swing.JPasswordField TxtConfirmPassword;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
